#
###################################
# Site wide configuration
####################################
#
title: myogg
email: xxjss@hotmail.com
description: myogg's blog,powered by jekyll.
url: https://myogg.github.io # the base hostname & protocol for your site
keywords: ["jekyll", "java", "scala","blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/xi'an
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-gist
  - jemoji

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: myogg
  avatar: avatar.jpg
  job: "blog & jekyll theme"
  bio: "A backend developer who loves design awesome things. Working for Dianping at in xi'an, China."
  email: xxjss@hotmail.com
  disqus-shortname: #username
  twitter:  Jlengyu
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: myogg #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
# Disqus settings

# disqus_username: Lucy
// 添加这个就行,上面的只是为了你能方便找到地方
gitalk:
    enable: true
    owner: myogg
    repo: myogg.github.io
    clientID: Ov23liFQJrMHaPJlrobq
    clientSecret: b72ef6f3bc0baba34845b9e251eaa59ad61ac8e2
    admin: myogg
